"""
Shared fixtures for critic-generated tests.

These tests capture CLAUDE.md violations and serve as permanent quality gates.
Generated by 5 parallel critics:
- Security: OWASP, injection, XSS, auth
- Architecture: SOLID, coupling, patterns
- Deception: Mocks, TODOs, placeholders
- Performance: N+1, memory, algorithms
- Code Quality: DRY, complexity, coverage
"""

import pytest
from pathlib import Path


# Base paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
ANALYSIS_FILE = PROJECT_ROOT / "20260204_OscGrid_Photonic_Quantum_Analysis.py"


@pytest.fixture
def project_root():
    """Return the project root directory."""
    return PROJECT_ROOT


@pytest.fixture
def analysis_file():
    """Return the main analysis file path."""
    return ANALYSIS_FILE


@pytest.fixture
def analysis_content():
    """Load and return the analysis file content."""
    return ANALYSIS_FILE.read_text()


@pytest.fixture
def analysis_lines():
    """Return the analysis file as a list of lines."""
    return ANALYSIS_FILE.read_text().splitlines()


# Physical constants for validation
@pytest.fixture
def physical_constants():
    """Known physical constants for verification."""
    return {
        "planck_constant": 6.62607015e-34,  # J·s (exact, SI 2019)
        "speed_of_light": 299792458,  # m/s (exact, SI definition)
        "wavelength_1550nm": 1550e-9,  # m
    }
